package:
  name: respyte
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - PyYAML
    - scipy


test:
  requires:
    - pytest
  imports:
    - respyte

about:
  home: add_url_here
  license: BSD-3-Clause License
